language: ruby
rvm:
  - 2.4.1

script:
  bundle exec jekyll build

deploy:
  provider: s3
  bucket: feabgoias.org
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_DEFAULT_REGION
  skip_cleanup: true
  local_dir: ./_site

branches:
  only:
  - master

cache: bundler

notifications:
  email: false
