language: ruby
rvm:
  - 2.3.7

install:
- sudo pip install awscli
script:
  bundle exec jekyll build

deploy:
  provider: s3
  bucket: feabgoias.org
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_DEFAULT_REGION
  skip_cleanup: true
  local_dir: ./_site

branches:
  only:
  - master

cache: bundler

after_deploy:
  aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/index.html"
